CREATE TABLE TABLE_DATA_1
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_DATA_2
(
no number(10),
create_date DATE
);

CREATE TABLE TABLE_COLC
(
std_date DATE,
CHECK_DATA1 VARCHAR2(6),
CHECK_DATA2 VARCHAR2(6)
);

INSERT INTO TABLE_DATA_1 VALUES (1, '2023-04-01');
INSERT INTO TABLE_DATA_1 VALUES (2, '2023-04-02');
INSERT INTO TABLE_DATA_1 VALUES (3, '2023-04-03');
INSERT INTO TABLE_DATA_1 VALUES (4, '2023-04-04');

INSERT INTO TABLE_DATA_2 VALUES (1, '2023-04-02');
INSERT INTO TABLE_DATA_2 VALUES (2, '2023-04-03');
INSERT INTO TABLE_DATA_2 VALUES (3, '2023-04-04');
INSERT INTO TABLE_DATA_2 VALUES (4, '2023-04-05');

/*******************************************/
MERGE INTO TABLE_COLC c
USING (
    SELECT DISTINCT create_date AS std_date
    FROM TABLE_DATA_1
) d
ON (c.std_date = d.std_date)
WHEN MATCHED THEN
    UPDATE SET c.CHECK_DATA1 = 'Y'
WHEN NOT MATCHED THEN
    INSERT (std_date, CHECK_DATA1, CHECK_DATA2)
    VALUES (d.std_date, 'Y', 'N');

MERGE INTO TABLE_COLC c
USING (
    SELECT DISTINCT create_date AS std_date
    FROM TABLE_DATA_2
) d
ON (c.std_date = d.std_date)
WHEN MATCHED THEN
    UPDATE SET c.CHECK_DATA2 = 'Y'
WHEN NOT MATCHED THEN
    INSERT (std_date, CHECK_DATA1, CHECK_DATA2)
    VALUES (d.std_date, 'N', 'Y');

SELECT std_date,
       CHECK_DATA1,
       CHECK_DATA2
FROM TABLE_COLC
ORDER BY std_date;
